EGC-23-24/decide-part-lorca

- decide/census/templates/census/import_census.html
- decide/census/urls.py
- decide/census/views.py
- requirements.txt
Now you can import the census of a voting from an Excel file.
Refs #4
> feat: Import census

- decide/census/models.py
- decide/census/tests.py
Export census has been tested.
Refs #4
> test: Test export census

- decide/census/tests.py
- decide/census/views.py
Import census has been tested.
Refs #4
> test: Test import census

- decide/visualizer/tests.py
changed the value of headless so that selenium is not opened
> test(update): MODIFIED HEADLESS VALUE

- .github/workflows/django.yml
> conf: change django.yml #22

- .gitmessage.txt
- decide/voting/models.py
- decide/voting/serializers.py
Serializers have been updated to include the new models and fields.
> feat: Ranked voting successfully visualized #12

- decide/booth/templates/booth/booth.html
Updated Booth to properly show a multiple option question
refs #93
> feat: Booth updated for multiple choice questions

- .github/workflows/django.yml
Update the django.yml to set up the continuous integration in your branch.
This PR will resolve the incident #78
> conf: Updated django.yml #78

- decide/booth/templates/booth/booth.html
This PR solve the incident #135 as requested, in this case for the comment voting.
> fix: Add voting_type in comment voting #135

- decide/voting/tests.py
Added tests for creating a multiple choice voting, more testing to be done involving other modules. It might be a good idea to wait until all types of votings are merged, since store and postproc will probably change and render current tests useless.
> test: Test multiple choice voting #55

- decide/visualizer/templates/visualizer/visualizer.html
- decide/visualizer/views.py
I have created the visualizer for the voting type "Yes/No", you can see it by creating a "voting" of type "Yes/No question" and then when doing "Tally" you have to enter the url:
```
http://localhost:8000/visualizer/[votingID]/
``` 
This PR will resolve the incident #140
> feat: Implemented visualizer for yes/no vote #140

- decide/visualizer/templates/visualizer/visualizer.html
- decide/visualizer/views.py
I have created the visualizer for the voting type "Ranked", you can see it by creating a "voting" of type "Ranked question" and then when doing "Tally" you have to enter the url:
```
http://localhost:8000/visualizer/[votingID]/
``` 
This PR will resolve the incident #158
> feat: Implemented visualizer for ranked vote #158

- .github/workflows/django.yml
Trigger action workflow when pull request is labeled "ready" and updated versions of python and postgres in action workflow
> conf: Changed pull request type github action #174

- .github/workflows/django.yml
- decide/voting/models.py
- decide/voting/tests.py
Test Complete Voting fixed so it can pass and the django.yml file has been updated with the ready tag #170
> Fix/error in comment voting tests voting #170

- decide/booth/templates/booth/booth.html
Added a comma in the booth.html file at line 333.
> fix: Added a comma in booth.html #170

- decide/store/tests.py
This PR solve the incident #207
> fix: Remove yes/no questions in choice cases #207

- decide/booth/templates/booth/booth.html
This PR solve the incident #209
> fix: Add post data in multiple choice button #209

- decide/booth/templates/booth/booth.html
> fix: Add voting type in classic voting booth #220

- decide/census/templates/census/census_details.html
Changing the census details view so that everything is written in English.
> fix(census): Changing the census details view #224

- decide/census/models.py
- decide/census/views.py
Census cannot be created with a non-existent voting id or voter id
> fix(census): Correcting census creation errors #232

- decide/booth/test_selenium.py
Waits for the elements to be present on the page before interacting with them.
> fix: Correct booth tests when performing ci #230

- .github/workflows/django.yml
- .github/workflows/release.yml
A new file release.yml create the new release when a tag is pushed.
> conf: Autmatic release #157

- decide/census/tests.py
Fixing the census tests so that they run correctly in GitHub Actions and can merge to develop
> fix(census): Correcting errors in census tests #241

- decide/census/tests.py
Fixing the census tests so that they run correctly in local
> fix(census): Correcting new errors in census tests #241

- decide/booth/templates/booth/booth.html
Calls PostData when submitting a multiple choice vote
> fix: Correct postdata in multiple choice #250

- decide/booth/templates/booth/booth.html
Corrects identation and removes unused variables
> refactor: Correct preference booth syntax #249

- decide/booth/test_selenium.py
Changed some configuration lines in test_selenium file so the test can pass. Also fixed the yes/no voting tests
This PR solve the incident #256
> fix: Change selenium test for both #256

- decide/store/tests.py
Fixed the store tests to run correctly in GitHub Actions and merge to develop.
> fix(census): Fixing the store tests #247

- decide/voting/models.py
This PR solve the incident #272
> fix: Add ranked question type to models #272

- decide/store/tests.py
The store tests have been fixed and all of them are working correctly.
> fix(census): Fixing the store tests definitively #247

- decide/base/templates/base2.html
- decide/base/templates/home.html
- decide/voting/test_configurator_selenium.py
- decide/voting/urls.py
> feat:Add configurator selenium test  #133

- decide/census/test_selenium.py
- decide/census/tests.py
Selenium tests have been moved to a new file test_selenium.py
> fix(census): Moving selenium test to a new file #283

- decide/census/test_selenium.py
- decide/census/tests.py
The selenium tests have been refactored.
> Refactoring census tests #285

- .github/workflows/django.yml
- .github/workflows/issues.yml
This PR solve the incident #281
> conf: Create automatic CI issue creator #281

- .github/workflows/issues.yml
The issues.yml file has been added to the branch
> conf(census): Adding issues.yml #51

- doc/Gestion-de-repositorio.md
The section _Estrategia de ramificación_ has been updated.
Solves #306
> doc: Updated branch strategy #306

- doc/proceso-de-gestion-de-incidencias.md
I have added an explanation of what to do when a issue is discarded and an explanation of how to create branches to resolve an issue.
Solves #305
> doc: Updated incident management #305

- decide/visualizer/test_selenium.py
I have added the tests for preference voting to the visualizer module
This PR resolve the incident #236
> fix: add preference voting test in visualizer #236

- decide/booth/templates/booth/booth.html
- decide/booth/views.py
> fix: Handle maxOption error #334

- decide/booth/templates/booth/booth.html
- decide/booth/test_selenium.py
- decide/booth/views.py
To run the refactored tests locally, you must execute these commands:
```
./manage.py test booth.test_selenium.MultipleChoiceQuestionBoothTest  -v 2
```
```
./manage.py test booth.test_selenium.YesNoBoothTest  -v 2
```
```
./manage.py test booth.test_selenium.CommentBoothTest  -v 2
```
```
./manage.py test booth.test_selenium.PreferenceBoothTest  -v 2
```
> fix: Refactor selenium tests #320

- decide/authentication/serializers.py
- decide/authentication/test_selenium.py
- decide/authentication/tests.py
- decide/authentication/views.py
- decide/booth/test_selenium.py
- decide/booth/tests.py
- decide/booth/views.py
- decide/postproc/tests.py
- decide/postproc/views.py
- decide/visualizer/test_selenium.py
- decide/visualizer/views.py
I have written comments for the classes and methods of my assigned modules.
This PR resolves the incident #341
> doc: Made comments in the modules #341

- doc/Informe-de-pruebas.md
Added load test description and updated dynamic selenium tests commands. This PR solves #321
> doc: Add load test description #321

- decide/authentication/templates/authentication/login.html
- decide/authentication/templates/authentication/register.html
- decide/authentication/test_selenium.py
- decide/base/templates/base2.html
- decide/base/templates/home.html
- decide/booth/templates/booth/booth.html
- decide/census/templates/census/census.html
- decide/census/templates/census/export_census.html
- decide/census/templates/census/import_census.html
- decide/visualizer/templates/visualizer/visualizer.html
- decide/voting/templates/list_votings.html
Some general styles of Decide! have been improved.
Solves #346
> fix: Improved decide style #346

- doc/Informe-de-pruebas.md
I have included a new test class that must be executed in a local environment.
Solves #358
> doc: Updated test report

- requirements.txt
This resolves #371 
Added locust to requirements.txt
> conf: Add locust to requirements #371
